version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "davai-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "davai-server"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\" DBUsername=\"postgres\""
image_repositories = []
resolve_s3 = true
disable_rollback = false

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"
