version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325" # management GUI (optional)
    environment:
      - ELASTICMQ_CONFIG_FILE=/opt/elasticmq.conf
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

volumes:
  postgres_data:

